// The Supabase Auth email templates (supabase/email-templates/) are generated
// from the shared branded layout by scripts/build-auth-emails.mjs. These fail
// when a committed template has drifted from what the script renders — run
// `npm run emails:auth` and commit the result.
import { test } from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { AUTH_EMAILS, renderAuthEmail } from '../scripts/build-auth-emails.mjs'
import { brandEmail } from '../supabase/functions/_shared/email.ts'

const dir = new URL('../supabase/email-templates/', import.meta.url)
const committed = (file) => readFileSync(new URL(file, dir), 'utf8')
const count = (s, needle) => s.split(needle).length - 1

test('each committed template is exactly what the generator renders', () => {
  for (const def of AUTH_EMAILS) {
    assert.equal(committed(def.file), renderAuthEmail(def), `${def.file} is stale: run npm run emails:auth`)
  }
})

test('templates are paste-ready fragments with the Supabase variables left literal', () => {
  for (const def of AUTH_EMAILS) {
    const html = renderAuthEmail(def)
    assert.doesNotMatch(html, /<!doctype|<html|<head|<body/i, def.file)
    // Button href, link href and link text; the mark comes from the Site URL.
    assert.equal(count(html, '{{ .ConfirmationURL }}'), 3, def.file)
    assert.equal(count(html, '<img src="{{ .SiteURL }}/email-mark.png"'), 1, def.file)
    assert.doesNotMatch(html, /\.invalid|&#123;|%7B/, def.file)
    // Only the two variables Supabase provides; nothing else looks templated.
    assert.deepEqual([...new Set(html.match(/\{\{[^}]*\}\}/g))].sort(), ['{{ .ConfirmationURL }}', '{{ .SiteURL }}'])
  }
})

test('templates keep the shared layout: dark palette, heading, copy and footer', () => {
  for (const def of AUTH_EMAILS) {
    const html = renderAuthEmail(def)
    assert.match(html, /^<!-- Generated by scripts\/build-auth-emails\.mjs[^\n]*-->\n<style>/)
    assert.match(html, /@media \(prefers-color-scheme: dark\)/)
    assert.ok(html.includes(`>${def.heading}</h1>`), def.file)
    assert.ok(html.includes(`>${def.button}</a>`), def.file)
    for (const p of def.paragraphs) assert.ok(html.includes(p), `${def.file}: ${p}`)
    assert.match(html, /Budgeer · your money, your friends, sorted<br>[^<]*hobby project/)
  }
})

test('the fragment is the full document minus its wrapper', () => {
  const { html, fragment } = brandEmail({
    origin: 'https://dev.budgeer.com', heading: 'H', paragraphs: ['P'], cta: { label: 'Go', url: 'https://dev.budgeer.com/x' }, showLink: true,
  })
  const [style, content] = fragment.trimEnd().split('</style>\n')
  assert.ok(html.includes(`${style}</style>\n</head>`))
  assert.ok(html.includes(`<body class="bb-canvas" style="margin:0;padding:0;background:#faf8f4;">\n${content}\n</body></html>`))
})

test('the README lists every template with its file and subject', () => {
  const readme = committed('README.md')
  for (const def of AUTH_EMAILS) {
    assert.ok(readme.includes(`| ${def.template} | \`${def.file}\` | \`${def.subject}\` |`), def.file)
  }
})
