// The native app's strings (mobile-core/strings.mjs): every leaf of the
// web's dictionaries, as "ns:key" = "text" .strings lines, and the parity
// check that fails a build when Greek is out of step with English.
import test from 'node:test'
import assert from 'node:assert/strict'
import { PACKS, escapeStrings, flatten, parity, stringsFile } from '../mobile-core/strings.mjs'

test('ios strings: every key carries its namespace and every value is a string', () => {
  const flat = flatten(PACKS.en)
  assert.ok(Object.keys(flat).length > 1000)
  assert.equal(flat['shell:nav.home'], 'Home')
  assert.equal(flat['dashboard:overview.spent'], 'Spent')
  for (const [key, value] of Object.entries(flat)) {
    assert.match(key, /^[a-z]+:[A-Za-z0-9_.-]+$/, key)
    assert.equal(typeof value, 'string')
  }
})

test('ios strings: en and el have the same keys', () => {
  assert.deepEqual(parity(PACKS.en, PACKS.el), { missing: [], extra: [] })
  const short = { auth: { email: 'Email', password: { label: 'Password' } } }
  assert.deepEqual(parity(PACKS.en, short).extra, [])
  assert.ok(parity(PACKS.en, short).missing.includes('shell:nav.home'))
  assert.deepEqual(parity(short, { auth: { email: 'x', password: { label: 'y' }, more: 'z' } }), {
    missing: [], extra: ['auth:more'],
  })
})

test('ios strings: the .strings file escapes quotes, backslashes and newlines', () => {
  assert.equal(escapeStrings('say "hi"\\ok\nnext\ttab'), 'say \\"hi\\"\\\\ok\\nnext\\ttab')
  const file = stringsFile({ common: { a: 'He said "no"', b: { c: 'line\nbreak' } } })
  const lines = file.trim().split('\n')
  assert.equal(lines[0], '/* Generated by mobile-core/strings.mjs from src/locales. Do not edit. */')
  assert.deepEqual(lines.slice(1), ['"common:a" = "He said \\"no\\"";', '"common:b.c" = "line\\nbreak";'])
  assert.ok(stringsFile(PACKS.el).includes('"shell:nav.home" = "Αρχική";'))
})
