// Every word printed on the statements (the personal PDF/Excel statement and
// the group PDF), in one object. The builders take it as an argument that
// defaults to STATEMENT_TEXT (English), so a translation only has to pass an
// object of the same shape: built from the app's `t` in the active language
// on the device, or from a `_shared/i18n` dictionary on the server (see
// docs/I18N.md, "Server texts"). Amounts and dates are formatted elsewhere
// (money.ts fmtMinor, pdf.ts money, ISO dates) and stay as they are for now.
//
// The shared rule-currency notes (ruleFx.ts CONVERTED_NOTE, missingRatesNote)
// are the Home card's words too, so they stay with ruleFx.ts.

export const STATEMENT_TEXT = {
  // Every page's footer (pdf.ts Statement.finish).
  footer: 'Generated by Budgeer · budgeer.com',

  // The personal statement (generate-report).
  personal: {
    // Row labels when a transaction has no category of its own.
    groupFallback: 'Group',
    uncategorized: 'Uncategorized',
    ruleFallback: 'Expense',

    // Notes under the totals: one short line each (the PDF's note box, the
    // Summary sheet).
    pending: (count: number, currencies: string[]): string => {
      const [what, verb, isnt] = count === 1
        ? ['1 transaction', 'awaits', 'isn’t']
        : [`${count} transactions`, 'await', 'aren’t']
      return `${what} in ${currencies.join(', ')} ${verb} an exchange rate and ${isnt} in the totals.`
    },
    yearlySpread: 'Totals count yearly subscriptions month by month, including charges paid before this period.',
    yearlySeparate: 'Yearly subscriptions are kept out of the totals (see Yearly subscriptions).',
    savingsFromIncome: 'Savings aren’t income; those taken from your income are subtracted from the net.',
    savingsReceived: 'Savings aren’t income and don’t change the net (see Saved).',
    fromSavings: 'Expenses paid from savings count as spending but not against your income.',
    salary: (day: number): string => `Salary paid from day ${day} of a month counts toward the next month's totals.`,

    // A yearly payment's mark: "Yearly · 10.00 EUR/mo".
    yearly: 'Yearly',
    everyYears: (years: number): string => `Every ${years} years`,
    perMonthSuffix: '/mo',
    fromSavingsMark: 'From savings',

    // The PDF.
    title: 'Financial statement',
    income: 'Income',
    spent: 'Spent',
    net: 'Net',
    whereTitle: 'Where your money went',
    whereSubtitle: (spent: string): string => `${spent} spent, by category`,
    savedTitle: 'Saved',
    savedAside: 'Not counted as income',
    savedInPeriod: 'Saved in this period',
    takenFromIncome: 'Taken from income',
    received: 'Received',
    yearlyTitle: 'Yearly subscriptions',
    yearlyAside: 'Kept out of the totals',
    paidInPeriod: 'Paid in this period',
    activePerYear: 'Active subscriptions, per year',
    perMonth: 'Per month',
    colPaid: 'Paid',
    colPayment: 'Payment',
    colAmountIn: (base: string): string => `Amount (${base})`,
    colSubscription: 'Subscription',
    colNextCharge: 'Next charge',
    colCharge: 'Charge',
    colPerYear: 'Per year',
    transactionsTitle: 'Transactions',
    transactionsAside: (n: number): string => `${n} in this period`,
    noTransactions: 'No transactions in this period.',
    colDate: 'Date',
    colCategory: 'Category',
    colDescription: 'Description',

    // The Excel workbook.
    sheetSummary: 'Summary',
    sheetTransactions: 'Transactions',
    sheetYearly: 'Yearly subscriptions',
    summaryHeading: 'Financial Statement',
    baseCurrency: 'Base currency',
    totalIncome: 'Total income',
    totalExpenses: 'Total expenses',
    paidFromSavings: 'Of which paid from savings',
    savedNotIncome: 'Saved (not income)',
    savedFromIncome: 'Saved from income',
    savedReceived: 'Saved, received',
    spendingByCategory: 'Spending by category',
    colType: 'Type',
    colCurrency: 'Currency',
    colAmount: 'Amount',
    colYearly: 'Yearly',
    ratePending: 'Rate pending',
    // The Type column: the row's kind, or a savings entry's source.
    kind: { income: 'income', expense: 'expense' } as Record<string, string>,
    kindFromSavings: (kind: string): string => `${kind} (from savings)`,
    savedFrom: { 'from income': 'saved (from income)', received: 'saved (received)' },
    yearlyHeading: 'Yearly subscriptions (kept out of the totals)',
    paidInPeriodIn: (base: string): string => `Paid in this period (${base})`,
    activePerYearIn: (base: string): string => `Active subscriptions per year (${base})`,
    perMonthIn: (base: string): string => `Per month (${base})`,
    paymentsInPeriod: 'Payments in this period',
    activeYearly: 'Active yearly subscriptions',
  },

  // The group statement (group-report).
  group: {
    title: 'Group statement',
    meta: (currency: string, members: number, today: string): string =>
      `${currency}   ·   ${members} members   ·   as of ${today}`,
    totalSpent: 'Total spent',
    expenses: 'Expenses',
    settlements: 'Settlements',
    balances: 'Balances',
    settledUp: 'Settled up',
    unknownMember: '—',
    whoOwesWhom: 'Who owes whom',
    paymentsSettle: (n: number): string => `${n} ${n === 1 ? 'payment settles' : 'payments settle'} everyone up`,
    everyoneSettled: 'Everyone is settled up.',
    expensesAside: (n: number): string => `${n} in total`,
    noExpenses: 'No expenses yet.',
    colDate: 'Date',
    colExpense: 'Expense',
    colPaidBy: 'Paid by',
    colSplit: 'Split',
    colAmount: 'Amount',
    expenseFallback: 'Expense',
    ratePending: 'Rate pending',
    noSettlements: 'No settlements recorded.',
    colFrom: 'From',
    colTo: 'To',
    activityTitle: 'Activity log',
    noActivity: 'No activity yet.',
    colWhen: 'When',
    colActivity: 'Activity',
  },
}

export type StatementText = typeof STATEMENT_TEXT
export type PersonalText = StatementText['personal']
