// The native app's strings, from the web's dictionaries (src/locales):
//   npm run ios:strings  →  ios/Budgeer/Budgeer/Resources/Generated/<lang>.lproj/Localizable.strings
// One .strings file per language, every leaf as "ns:path.to.key" = "text",
// the same key the web's t() takes, so the two apps share one wording. The
// files are generated (never committed): the Xcode scheme's pre-action and
// CI run this before a build.
//
// Parity: a key present in one language and not the other fails the run
// (exit 1), so CI can't ship a screen that falls silent in Greek. The web's
// own test (test/i18n.test.js) checks the same thing on every push; this is
// the build-time copy for a machine that only builds the app.
//
// Strings with {{placeholders}} or plural forms are written too, but the app
// reads those through the core (i18n.t, which interpolates and picks the
// plural as the web does) rather than filling them in Swift.
import { mkdir, writeFile } from 'node:fs/promises'
import { resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import en from '../src/locales/en/index.js'
import el from '../src/locales/el/index.js'

export const ROOT = resolve(fileURLToPath(new URL('..', import.meta.url)))
export const STRINGS_DIR = 'ios/Budgeer/Budgeer/Resources/Generated'
export const PACKS = { en, el }

// { 'ns:a.b.c': 'text' } for every leaf of a language's dictionaries.
export function flatten(pack) {
  const out = {}
  const walk = (obj, prefix, into) => {
    for (const [k, v] of Object.entries(obj)) {
      const key = prefix ? `${prefix}.${k}` : k
      if (v && typeof v === 'object') walk(v, key, into)
      else into[key] = String(v)
    }
  }
  for (const [ns, dict] of Object.entries(pack)) {
    const flat = {}
    walk(dict, '', flat)
    for (const [k, v] of Object.entries(flat)) out[`${ns}:${k}`] = v
  }
  return out
}

// The keys `lang` lacks that the reference has, and the extra ones it has.
export function parity(reference, lang) {
  const want = Object.keys(flatten(reference))
  const got = new Set(Object.keys(flatten(lang)))
  const wantSet = new Set(want)
  return {
    missing: want.filter((k) => !got.has(k)),
    extra: [...got].filter((k) => !wantSet.has(k)),
  }
}

// A .strings literal: backslash, double quote, newline, tab escaped.
export const escapeStrings = (s) =>
  s.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n').replace(/\t/g, '\\t')

// The file for one language, keys sorted so a diff is readable.
export function stringsFile(pack) {
  const flat = flatten(pack)
  const lines = ['/* Generated by mobile-core/strings.mjs from src/locales. Do not edit. */']
  for (const key of Object.keys(flat).sort()) lines.push(`"${escapeStrings(key)}" = "${escapeStrings(flat[key])}";`)
  return lines.join('\n') + '\n'
}

export async function writeStrings(root = ROOT) {
  const { missing, extra } = parity(PACKS.en, PACKS.el)
  if (missing.length || extra.length) {
    throw new Error(`ios strings: el is out of step with en\n  missing: ${missing.join(', ') || '-'}\n  extra: ${extra.join(', ') || '-'}`)
  }
  for (const [lang, pack] of Object.entries(PACKS)) {
    const dir = resolve(root, STRINGS_DIR, `${lang}.lproj`)
    await mkdir(dir, { recursive: true })
    await writeFile(resolve(dir, 'Localizable.strings'), stringsFile(pack))
  }
  return Object.keys(flatten(PACKS.en)).length
}

const isMain = process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)
if (isMain) {
  try {
    const n = await writeStrings()
    console.log(`ios strings: ${n} keys × ${Object.keys(PACKS).length} languages → ${STRINGS_DIR}`)
  } catch (err) {
    console.error(err.message)
    process.exit(1)
  }
}
